'use client';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6uq2dRo0Nev
 */
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { FormEvent, useState } from 'react';
import { currentTimeZoneToIsoString } from '@/lib/utils';
import { submitCommitAction } from '@/app/actions/commit';
import { toast } from 'react-toastify';

export function Form() {
  const [commitAmount, setCommitAmount] = useState<number>(1);
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setIsSubmitting(true);

    try {
      const formData = new FormData(event.currentTarget);

      await toast.promise(
        submitCommitAction(formData),
        {
          pending: 'Committing...',
          success: 'Successfully committed!',
          error: 'Failed to commit.',
        }
      );
    } catch (error) {
      console.error('Error submitting form:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <section className="w-full flex justify-center items-center">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-8 text-center">
          <form className="w-full max-w-md space-y-4" onSubmit={handleSubmit}>
            <div className="space-y-2">
              <Label htmlFor="commit-message">Commit Message</Label>
              <Input
                name="commitMessage"
                id="commit-message"
                placeholder="Enter your commit message"
                required
              />
            </div>
            <div className="flex space-x-4 items-end">
              <div className="space-y-2 w-1/2 mb-2">
                <Label htmlFor="commit-date">Commit Date</Label>
                <Input
                  name="customTime"
                  defaultValue={currentTimeZoneToIsoString()}
                  id="commit-date"
                  type="datetime-local"
                  required
                />
              </div>
              <div className="space-y-2 w-1/2 mb-2 flex flex-col items-center justify-end">
                <Label className="mb-[5px]" htmlFor="commit-amount">
                  Commit Amount
                </Label>
                <div className="w-full flex justify-between items-end">
                  <Input
                    className="w-1/2 mr-2"
                    name="commitAmount"
                    value={commitAmount}
                    id="commit-amount"
                    max="99"
                    min="1"
                    type="number"
                    onChange={(e) => setCommitAmount(Number(e.target.value))}
                    required
                  />
                  <div className="flex justify-between w-1/2">
                    <Button
                      className="w-1/2 mr-2"
                      type="button"
                      onClick={() =>
                        setCommitAmount((prev) =>
                          prev === 1 ? prev : prev - 1,
                        )
                      }
                    >
                      -1
                    </Button>
                    <Button
                      className="w-1/2"
                      type="button"
                      onClick={() =>
                        setCommitAmount((prev) =>
                          prev === 99 ? prev : prev + 1,
                        )
                      }
                    >
                      +1
                    </Button>
                  </div>
                </div>
              </div>
            </div>
            <Button className="w-full" type="submit" disabled={isSubmitting}>
              {isSubmitting ? 'Submitting...' : 'Submit'}
            </Button>
          </form>
        </div>
      </div>
    </section>
  );
}
